Remove python 3.6 from testing
Github Actions do not support python 3.6 on `ubuntu-latest`*, 
and since python 3.6 is well after its end of life, I see no use in hacking a way for it work.

Farewell python 3.6, you were great


*```
Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```