IBM→ BiomedSciAI Github org transfer adjustments (#51)
Summary:
1. Replace Travis CI with Github Actions workflows
    - Discard support for Python 3.6
2. Update 3rd-party services linking to the repo
3. Update internal hyperlinks pointing to the repo
4. Limit scikit-learn and numpy version for passing tests
   Fix support in the future

----------------------------------------------------

* Initial GitHub Actions workflow for building and testing

Signed-off-by: Ehud-Karavani <ehud.karavani@ibm.com>

* Fix bad indentation on workflows test yaml

* Change build platform to `linux`

Seems like there are no python builds on Ubuntu
https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

* Run py-version matrix independent of versions fail

Don't cancel other the rest of the python version builds if only one (or more, just make them independent) fail.

It is not uncommon that only certain python versions fail due to dependency hell.

* Install `contrib` dependencies

Since `hemm` failed due to no Pytorch

* Add print final dependencies

Also rename job

* Run in fail fast

Test whether only one version succeeding is a matter of some resource parallel allocation mutex.

* Try a better way to enforce sequential run

Revert the `fail-fast`, but now try to ensure that there are no parallel jobs by using `max-parallel`

* Limit scikit-learn version to <1.2.0

Currently causes two main issues:
 - No `normalize` in `LinearRegression`.
   Easy, just need to update tests to use a Pipeline
 - Force singular feature type in pandas columns (harder)
    Harder, will require a safe-join mechanism when adding treatment as variable.

* Add Github Actions-based CI status badge

Workflow's name appear in the badge, so change that to a short `Build`
instead of a long "Build and install causallib".
Consequentially change the yml file from `test` to `build` to preserve
consistency

Signed-off-by: Ehud-Karavani <ehud.karavani@ibm.com>

* Publish coverage report to CodeClimate

* Specific `paambaati/codeclimate-action` version

* Limit numpy version to <1.24.0

Currently causes a problem with matplotlib when plotting `fill_between` in the calibration plot tests

* Dummy change to trigger Github Actions

* Update build.yml

* Remove python 3.6 from testing

Github Actions do not support python 3.6 on `ubuntu-latest`*, 
and since python 3.6 is well after its end of life, I see no use in hacking a way for it work.

Farewell python 3.6, you were great


*```
Error: The version '3.6' with architecture 'x64' was not found for Ubuntu 22.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

* Update CodeClimate coverage badge to new URL

Signed-off-by: Ehud-Karavani <ehud.karavani@ibm.com>

* Remove Travis configuration file

Goodbye, Travis, thank you for your service.

Signed-off-by: Ehud-Karavani <ehud.karavani@ibm.com>

* Remove single process constraint

Check whether build now passes when removing the single process constraint and allowed to run in parallel

* Change hyperlink references from IBM Github org to BiomedSciAI

Signed-off-by: Ehud-Karavani <ehud.karavani@ibm.com>

Signed-off-by: Ehud-Karavani <ehud.karavani@ibm.com>
Co-authored-by: Sagi Polaczek <56922146+SagiPolaczek@users.noreply.github.com>